services:
  - type: web
    name: military-ams-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn military_ams.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: military-ams-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: ALLOWED_HOSTS
        sync: false

databases:
  - name: military-ams-db
    databaseName: postgres_28vl
    user: postgres_28vl_user
    plan: free
    region: oregon
